### ISSUE TITLE
The dictionary AttrDict is not deepcopiable

### ISSUE THREAD

**Issue by AnandTella** [Grk0/python-libconf#13]
The deepcopy of the AttrDict is failing as the "__getattr__" doesn't raise AttributeError for non existing attributes. 

The getattr(x, "__deepcopy__", None) is invoked internally on deepcopy.
The attribute "__deepcopy__" is not present and hence KeyError is raised by "__getitem__" but AttributeError is expected from "__getattr__"

**Comment by Grk0** [comment]
Fixed in 2.0.0, thanks for your PR!
