### ISSUE TITLE
Setting with "%" failed to be parsed

### ISSUE THREAD

**Issue by StephaneG31** [Grk0/python-libconf#23]
We use libconfig in C++ for a long time.
We have some config file that works well with the C++ lib https://hyperrealm.github.io/libconfig/libconfig_manual.html, but not with this python lib.

For example :

**percent.cfg**
```
openvxi :
{
  client%2erec%2eimplementation : 
  {
    type = "VXIString";
    value = "openvxi";
  };
}`
````

**percent.py**
```python
import io, libconf

with io.open('percent.cfg') as f:
    config = libconf.load(f)
````

returns
```
    raise ConfigParseError(
libconf.ConfigParseError: Couldn't load config in 'percent.cfg' row 3, column 9: '%2erec%2eimplementat'
```

**is it possible to consider the char '%' valid in a setting key ?**

**Comment by ChrisAichinger** [comment]
Hi Stephane,
in my understanding, libconfig does not support percent signs in identifier names. See the definition of [`name` in libconfig's scanner.l](https://github.com/hyperrealm/libconfig/blob/master/lib/scanner.l#L59). The [documentation concurs](https://hyperrealm.github.io/libconfig/libconfig_manual.html#Compiling-Using-pkg_002dconfig):

> All names are case-sensitive. They may consist only of alphanumeric characters, dashes (‘-’), underscores (‘_’), and asterisks (‘*’), and must begin with a letter or asterisk. No other characters are allowed. 

I also tried loading your file with my libconfig (1.5-0.4 on Debian), and it gives an error: `example.cfg:3 - syntax error`. Here's my test program, that I compiled with `gcc -Wall -ggdb a.c -lconfig`:

        #include <libconfig.h>
        #include <stdio.h>
        #include <stdlib.h>

        int main() {
            config_t cfg;
            config_init(&cfg);
            if(! config_read_file(&cfg, "example.cfg"))
            {
                fprintf(stderr, "%s:%d - %s\n", config_error_file(&cfg),
                        config_error_line(&cfg), config_error_text(&cfg));
                config_destroy(&cfg);
                return(EXIT_FAILURE);
            }
            return 0;
        }

So maybe I misunderstood your issue, or you have custom patches in your version of libconfig to support percent signs. Could you please check on your end?

**Comment by StephaneG31** [comment]
Thanks for your fast reply.
I read more the code we have and the team who use libconfig on our site call some unescape function. so client%2erec%2eimplementation will be unescaped in client.rec.implementation (which seems to be not valid also).

I'm sorry for consuming your time, we have a weird implementation in our code that I need to understand.
