### ISSUE TITLE
Setting dynamically generated key of arbitrary depth

### ISSUE THREAD

**Issue by dhiraj113** [Grk0/python-libconf#5]
How to assign dynamically generated key, value pairs using the provided API?

Suppose, I have a key of format `field1.field2.field3...` but whose depth is known only at runtime. How to assign such a key value pair?

I ideally would like to be able to do something like this
```
config['window.title'] = value
```
Both the suggested options are not very helpful because

1. `config.window.title`  requires the strings `window` and `title` to be known at the time of code writing. However, in my use case, they are known only at runtime.
2. `config['window']['title']` requires the depth of key to be known at the time of code writing. However, for my use case, the depth is known only at runtime.

The provided API looks to be too restrictive and insufficient for the very basic case of assigning value to a key generated at runtime.

**Comment by Grk0** [comment]
The returned data structure is essentially a [tree](https://en.wikipedia.org/wiki/Tree_(data_structure)). You can traverse it with the common [tree traversal algorithms](https://en.wikipedia.org/wiki/Tree_traversal). That way you can decide at run-time what nodes you want to visit.

```python
def traverse(tree):
    for child in tree['children']:
        traverse(child)
    if tree['id'] == 12345:
        print("found")
```

libconf's return value is simply a Python representation of the libconfig document structure. I don't think there's much that can be changed here. If it's ok for you, I'd close this ticket.
