### ISSUE TITLE
Creating config on the fly

### ISSUE THREAD

**Issue by minihops** [Grk0/python-libconf#7]
Hi, thanks for providing this pice of software.
I want to use the lib for creating a configuration on the fly and write it to a file at the end.
Is there any sample for that? 
Thanks.
Christof

**Comment by Grk0** [comment]
Hi, you can build up a dictionary containing your configuration data over several steps, setting keys (and creating sub-dictionaries/lists/tuples) as you go along. 

Then you can serialize that dictionary to a string or to a file with libconf:
```python
d = dict()
# ... populate dictionary d here ...
config_str = libconf.dumps(d)
```

Hope that answers your question!
