### ISSUE TITLE
How to set a value as a long integer?

### ISSUE THREAD

**Issue by dhiraj113** [Grk0/python-libconf#9]
I would like to set a value as a long-integer in libconf. The output should appear as below in the created `.cfg` file

```
config['key'] = 1000000L
````

Is there some API to specify the data type of the value?

**Comment by Grk0** [comment]
Libconf will automatically switch to using the "L" suffix for numbers outside of the 32bit integer value. So the following would force an "L" suffix:
```
libconf.dumps({'key': 100000000000000000})
```
A smaller number, such as 1000000, would not get an "L" suffix, since it comfortably fits into a normal-sized integer.

**Comment by dhiraj113** [comment]
My use case requires `L` to be present for smaller integers as well. So, I guess I will have to resort to editing the generated config file. Thanks!
